[project]
name = "git-criollo"
version = "0.1.0"
description = "TUI para Git con interfaz limpieza"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "gitpython>=3.1.52",
    "textual>=8.2.8",
]

[project.scripts]
gitcriollo = "git_criollo.__main__:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
